version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nestle-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - nestle-network

  frontend:
    build: ./frontend
    container_name: nestle-frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - backend
    command: npm run dev
    networks:
      - nestle-network

networks:
  nestle-network:
    driver: bridge
