services:
  backend:
    build: ./backend
    container_name: apex-backend
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - apex-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: apex-frontend
    expose:
      - "3000"
    environment:
      - API_BASE_URL=http://nginx/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    depends_on:
      - backend
    command: npm run dev
    networks:
      - apex-network

  nginx:
    build: ./nginx
    container_name: apex-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - apex-network
    restart: unless-stopped

networks:
  apex-network:
    driver: bridge
